// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXAbnA8INbkaxiFe1fmnCpdFUffcGwCs',
    appId: '1:335039490958:web:81aeb65f4dca971065d2df',
    messagingSenderId: '335039490958',
    projectId: 'notes-34c19',
    authDomain: 'notes-34c19.firebaseapp.com',
    storageBucket: 'notes-34c19.appspot.com',
    measurementId: 'G-MQR15MP4S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPug8-h7BYFT9lcRZxGSjNDW3XCDblpk',
    appId: '1:335039490958:android:fab5265030ef0c9765d2df',
    messagingSenderId: '335039490958',
    projectId: 'notes-34c19',
    storageBucket: 'notes-34c19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHgXwNdNpDdijhcmDzBi_O-zWghO6EAM',
    appId: '1:335039490958:ios:4466c2c05f69b59d65d2df',
    messagingSenderId: '335039490958',
    projectId: 'notes-34c19',
    storageBucket: 'notes-34c19.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdHgXwNdNpDdijhcmDzBi_O-zWghO6EAM',
    appId: '1:335039490958:ios:56587e2d9ebed6d565d2df',
    messagingSenderId: '335039490958',
    projectId: 'notes-34c19',
    storageBucket: 'notes-34c19.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
